import React, { useEffect, useState } from "react";
import { UserPlus } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { PageHeader, Card, Loader, EmptyState, inputClass } from "@/components/portal/ui";
import { STAFF_ROLES } from "@/lib/roles";
import { adminList } from "@/lib/adminData";

export default function AdminUsers() {
  const [users, setUsers] = useState([]); const [profiles, setProfiles] = useState([]); const [roles, setRoles] = useState([]); const [email, setEmail] = useState(""); const [role, setRole] = useState("administrator"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const [allUsers, allProfiles, allRoles] = await Promise.all([adminList("User"), adminList("StaffProfile"), adminList("RolePermission", "-created_date", 200)]); setUsers(allUsers.filter((u) => u.role === "admin")); setProfiles(allProfiles); setRoles(allRoles.map((r) => r.role).filter(Boolean)); } catch (error) { setMessage(error.message || "Unable to load users"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function invite() { setMessage(""); try { await base44.functions.invoke("adminControl", { action: "invite_user", email, role: "admin" }); setMessage("Invitation sent. The user must complete Base44 registration before receiving a profile."); setEmail(""); } catch (error) { setMessage(error.message || "Invitation failed"); } }
  async function saveProfile(user, profile, nextRole, active) { try { const data = { user_id: user.id, full_name: profile?.full_name || user.full_name || "", email: user.email, staff_role: nextRole, active, is_owner: !!profile?.is_owner }; await base44.functions.invoke("adminControl", { action: "entity_mutation", entity: "StaffProfile", mutation: profile?.id ? "update" : "create", id: profile?.id, data, auditDetails: `Profile assigned to ${user.email}` }); load(); } catch (error) { setMessage(error.message || "Profile update failed"); } }
  if (loading) return <Loader />;
  const allRoles = [...new Set([...STAFF_ROLES.filter((item) => item !== "owner"), ...roles.filter((item) => item !== "owner")])];
  return <div><PageHeader title="Users" subtitle="Invite dashboard users and manage their roles" /><Card className="mb-6 p-5"><h2 className="font-serif-display text-lg font-semibold">Invite admin</h2><div className="mt-3 flex flex-wrap gap-2"><input type="email" className={inputClass + " max-w-sm"} placeholder="client@example.com" value={email} onChange={(e) => setEmail(e.target.value)} /><button onClick={invite} disabled={!email} className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><UserPlus className="h-4 w-4" /> Send invitation</button></div></Card>{message && <p className="mb-4 text-sm text-primary">{message}</p>}{users.length === 0 ? <EmptyState icon={UserPlus} title="No admin accounts" message="Invite the first dashboard user above." /> : <Card className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Email</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-border">{users.map((user) => { const profile = profiles.find((item) => item.user_id === user.id); return <tr key={user.id}><td className="px-4 py-3">{user.email}</td><td className="px-4 py-3"><select className={inputClass} value={profile?.is_owner ? "owner" : profile?.staff_role || "administrator"} disabled={profile?.is_owner} onChange={(e) => saveProfile(user, profile, e.target.value, profile?.active !== false)}>{profile?.is_owner && <option value="owner">Owner</option>}{allRoles.map((item) => <option key={item} value={item}>{item.replace("_", " ")}</option>)}</select></td><td className="px-4 py-3"><button onClick={() => saveProfile(user, profile, profile?.staff_role || "administrator", profile?.active === false)} className="text-primary hover:underline">{profile?.active === false ? "Activate" : "Deactivate"}</button></td></tr>; })}</tbody></table></Card>}</div>;
}
